version: "3.7"
services:
  app:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - app.env
  mysql:
    image: mysql
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
