version: "3.7"
services:
  app:
    build: .
    command: sleep infinity
    volumes:
      - ..:/original:cached
      - app:/app
      - home:/home/app
      - ~/.gitconfig:/home/app/.gitconfig:ro
      - ~/.zshrc:/home/app/.zshrc:ro
      - ~/.netrc:/home/app/.netrc:ro
      - ~/.gem:/home/app/.gem:ro
      - ~/.gem:/home/app/.gem/ruby
      - ~/.gem:/home/app/.gem/specs
    env_file:
      - app.env
  mysql:
    image: mysql
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
volumes:
  app:
  home:
